### ISSUE TITLE
Redesign the custom order of the rooms

### ISSUE THREAD

**Issue by RuslanSlobodian** [nromanen/Schedule#230]
#### Description
Redesign the functionality of saving the order of room entities  in order to provide the ability to return the sort order of rooms to the UI using the integer data type. Similar functionality has already been done for the Group entity.

Actual behavior: Rooms sort order saves in DB using Double data type.
Expected behavior: Rooms sort order saves in DB using Integer data type.

#### Tasks
- [x] Redesign the functionality
- [x] Made changes to Liquibase changeLog
- [x] Make changes to the relevant tests if necessary
![1](https://user-images.githubusercontent.com/23045634/171728585-c1887cfd-a9f6-4408-b34c-88fd2b2935a9.jpg)
