### ISSUE TITLE
Fix code style violations in tests

### ISSUE THREAD

**Issue by RuslanSlobodian** [nromanen/Schedule#236]
#### Description
Fix code style violations in tests.

#### Tasks
- [x] Correct code style violations that are present in test classes.
- [x] Define a separate rule for checking the names of test methods (to be able to use underscores )
- [x] Enable checkstyle for tests and change path to checkStyle reports in build.yml
